appName: app3
namespace: app3
pod:
  replicas: 2
  labels:
    app: app3
  image:
    repository: nginxdemos/hello
    tag: plain-text

  containerPort: 80

  resources:
    requests:
      memory: "16Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

ingress:
  host: "app3.guud1.space"
  class: "nginx-trial"