appName: app1
namespace: app1
pod:
  replicas: 2
  labels:
    app: app1
  image:
    repository: nginxdemos/hello
    tag: plain-text

  containerPort: 80

  resources:
    requests:
      memory: "16Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

ingress:
  host: "app1.guud1.space"
