apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  # TODO to values
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: frontend
  template:
    metadata:
      labels: "{{ .Values.labels.app }}:{{ .Values.labels.frontend }}"

    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        # TODO values
        ports:
        - containerPort: {{ .Values.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        # TODO move the whole resources section to the into values (example from ingress deamonset)
        resources:
{{ toYaml .Values.resources | indent 10 }}
