apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.pod.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: frontend
  template:
    metadata:
      labels: "{{ .Values.pod.labels.app }}:{{ .Values.pod.labels.frontend }}"

    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "{{ .Values.pod.image.name }}:{{ .Values.pod.image.tag }}"
        ports:
        - containerPort: {{ .Values.pod.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        resources:
{{ toYaml .Values.pod.resources | indent 10 }}
