apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
{{- if .Values.ingress.class }}
  annotations:
    # This is deprecated annotation, but it is required for GKE
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
{{- end }}
spec:
{{- if .Values.ingress.class }}
  ingressClassName: {{ .Values.ingress.class }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appName }}
            port:
              number: 80