apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.appName }}
          servicePort: 80
        